luffy_rbac/app01/urls.py
from django.urls import re_path
from .views import CustomerAddView, CustomerDelView, CustomerEditView, CustomerListView, PaymentAddView, PaymentDelView, PaymentEditView, PaymentListView, LoginView


urlpatterns = [

    re_path(r'^customer/list/$', CustomerListView.as_view(), name="customer_list"),
    re_path(r'^customer/add/$', CustomerAddView.as_view(), name="customer_add"),
    re_path(r'^customer/edit/(?P<cid>\d+)/$', CustomerEditView.as_view(), name="customer_edit"),
    re_path(r'^customer/del/(?P<cid>\d+)/$', CustomerDelView.as_view(), name="customer_del"),
    # re_path(r'^customer/import/$', customer.customer_import),
    # re_path(r'^customer/tpl/$', customer.customer_tpl),
    #
    re_path(r'^payment/list/$', PaymentListView.as_view(), name="payment_list"),
    re_path(r'^payment/add/$', PaymentAddView.as_view(), name="payment_add"),
    re_path(r'^payment/edit/(?P<pid>\d+)/$', PaymentEditView.as_view(), name="payment_edit"),
    re_path(r'^payment/del/(?P<pid>\d+)/$', PaymentDelView.as_view(), name="payment_del"),
    re_path(r'^login/$', LoginView.as_view(), name="login"),
]

luffy_rbac/luffy_rbac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app01.urls"))
]

luffy_rbac/app01/models.py
from django.db import models


class Customer(models.Model):
    """
    客户表
    """
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.CharField(verbose_name="年龄", max_length=32)
    email = models.EmailField(verbose_name="邮箱", max_length=32)
    company = models.CharField(verbose_name="公司", max_length=32)

    def __str__(self):
        return self.name


class Payment(models.Model):
    """
    付费记录
    """
    customer = models.ForeignKey(verbose_name="关联客户", to="Customer", on_delete=models.CASCADE)
    money = models.IntegerField(verbose_name="付费金额")
    create_time = models.DateTimeField(verbose_name="付费时间", auto_now_add=True)

luffy_rbac/rbac/models.py
# 基于角色的权限访问控制系统
from django.db import models


class Menu(models.Model):
    """
    菜单表
    """
    title = models.CharField(verbose_name="菜单名称", max_length=32)
    icon = models.CharField(verbose_name="图标", max_length=32)

    def __str__(self):
        return self.title


class Permission(models.Model):
    """
    权限表
    """
    title = models.CharField(verbose_name="标题", max_length=32)
    url = models.CharField(verbose_name="含正则的URL", max_length=128)
    # is_menu = models.BooleanField(verbose_name="是否可做菜单", default=False)
    # icon = models.CharField(verbose_name="菜单图标", max_length=32, null=True, blank=True)
    menu = models.ForeignKey(verbose_name="所属菜单", to=Menu, null=True, blank=True, help_text='null表示不是菜单;非null表示是二级菜单', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色
    """
    title = models.CharField(verbose_name="角色名称", max_length=32)
    permissions = models.ManyToManyField(verbose_name="拥有的所欲权限", to="Permission", blank=True)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """
    用户表
    """
    name = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.CharField(verbose_name="邮箱", max_length=32)
    roles = models.ManyToManyField(verbose_name="拥有的所有角色", to=Role, blank=True)

    def __str__(self):
        return self.name

luffy_rbac/app01/forms.py
from django.forms import ModelForm
from .models import Customer, Payment


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
        self.fields['customer'].empty_label = "请选择客户"


class PaymentUserForm(ModelForm):
    class Meta:
        model = Payment
        exclude = ['customer', ]

    def __init__(self, *args, **kwargs):
        super(PaymentUserForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

luffy_rbac/app01/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Customer, Payment
from rbac.models import UserInfo
from .forms import CustomerForm, PaymentForm, PaymentUserForm
from django.http import HttpResponse
from rbac.service.init_permission import init_permission


class CustomerListView(View):
    def get(self, request):
        # 查询所有客户信息
        data_list = Customer.objects.all()
        return render(request, "customer_list.html", {"data_list": data_list})


class CustomerAddView(View):
    def get(self, request):
        """
        添加客户信息
        """
        form = CustomerForm()
        return render(request, "customer_add.html", {"form": form})

    def post(self, request):
        form = CustomerForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/customer/list/')
        return render(request, 'customer_add.html', {'form': form})


class CustomerEditView(View):
    """
    编辑客户信息
    """

    def get(self, request, cid):
        obj = Customer.objects.get(id=cid)
        form = CustomerForm(instance=obj)
        return render(request, "customer_edit.html", {"form": form})

    def post(self, request, cid):
        obj = Customer.objects.get(id=cid)
        form = CustomerForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('/customer/list/')
        return render(request, 'customer_edit.html', {'form': form})


class CustomerDelView(View):
    def get(self, request, cid):
        # 获取id
        Customer.objects.filter(id=cid).delete()
        return redirect("/customer/list/")


class PaymentListView(View):
    """
    付费列表
    """
    def get(self, request):
        data_list = Payment.objects.all()
        return render(request, "payment_list.html", {"data_list":data_list})


class PaymentAddView(View):
    """
    添加账单
    """
    def get(self, request):
        form = PaymentForm()
        return render(request, "payment_add.html", {"form": form})

    def post(self, request):
        form = PaymentForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/payment/list/")
        return render(request, "payment_add.html", {"form": form})


class PaymentEditView(View):
    def get(self, request, pid):
        obj = Payment.objects.get(id=pid)
        form = PaymentForm(instance=obj)
        return render(request, 'payment_edit.html', {'form': form})

    def post(self, request, pid):
        obj = Payment.objects.get(id=pid)
        form = PaymentForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('/payment/list/')
        return render(request, 'payment_edit.html', {'form': form})


class PaymentDelView(View):
    def get(self, request, pid):
        Payment.objects.filter(id=pid).delete()
        return redirect('/payment/list/')


class LoginView(View):
    def get(self, request):
        return render(request, "login.html")

    def post(self, request):
        # 获取登录的用户名密码
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        # 查库
        current_user = UserInfo.objects.filter(name=user, password=pwd).first()
        if not current_user:
            return render(request, "login.html", {"msg": "用户名或密码错误"})
        # 将用户信息放入session
        request.session["user_info"] = {"id": current_user.id, "name": current_user.name}
        # 登录后初始化权限
        init_permission(current_user, request)
        return redirect("/customer/list")

luffy_rbac/rbac/views.py
from django.shortcuts import render

# Create your views here.

luffy_rbac/app01/templates/customer_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

luffy_rbac/app01/templates/customer_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

luffy_rbac/app01/templates/customer_import.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <div
                        style="position: relative;display: inline-block;height: 50px;min-width: 300px;overflow: hidden;">
                    <div style="position: absolute;top: 0;left: 0;right: 0;bottom: 0;z-index: 1000;border: 1px dotted #9d9d9d;color: #9d9d9d;line-height: 50px;padding-left: 15px;">
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                        <span>点击上传Excel文件</span>
                    </div>
                    <input name="customer_excel" type="file" id="excelFile"
                           style="position: absolute;top: 0;left: 0;right: 0;bottom: 0;background-color: #333333;z-index: 1001;opacity: 0;filter:alpha(opacity=0);">
                </div>
                <p class="help-block">注意：批量导入的Excel需使用规定格式模板. <a href="/customer/tpl/">下载模板</a></p>
            </div>
            <button type="submit" class="btn btn-primary">上传</button>
            {% if status %}
                <span style="color: green;">{{ msg }}</span>
            {% else %}
                <span style="color: red;">{{ msg }}</span>
            {% endif %}
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#excelFile').change(function (e) {
                var fileName = e.currentTarget.files[0].name;
                $(this).prev().find('span').text(fileName);
            })
        })
    </script>
{% endblock %}

luffy_rbac/app01/templates/customer_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="/customer/add/">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加客户
            </a>
            <a class="btn btn-default" href="/customer/import/">
                <i class="fa fa-file-excel-o" aria-hidden="true"></i> 批量导入
            </a>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>客户姓名</th>
                <th>年龄</th>
                <th>邮箱</th>
                <th>公司</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.age }}</td>
                    <td>{{ row.email }}</td>
                    <td>{{ row.company }}</td>
                    <td>
                        <a style="color: #333333;" href="/customer/edit/{{ row.id }}/">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="/customer/del/{{ row.id }}/"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

luffy_rbac/app01/templates/layout.html
{#{% load staticfiles %}#}
{% load static %}
{% load rbac %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>路飞学城</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <link rel="stylesheet" href="{% static 'rbac/rbac.css' %} "/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }
    </style>
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">路飞学城 </span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item">资产管理</a>
            <a class="menu-item">用户信息</a>
            <a class="menu-item">路飞管理</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">管他什么菜单</a>
                    <a href="#" class="more-item">实在是编不了</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="#" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            {% menu request %}
        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                <li><a href="#">首页</a></li>
                <li class="active">客户管理</li>

            </ol>
        </div>
        {% block content %} {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
{% block js %} {% endblock %}
</body>
</html>

luffy_rbac/app01/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>用户登录</h1>
<form method="post">
    {% csrf_token %}
    <input type="text" name="user" placeholder="请输入用户名">
    <input type="password" name="pwd" placeholder="请输入密码">
    <input type="submit" value="提交"><span style="color: red">{{ msg }}</span>
</form>

</body>
</html>

luffy_rbac/app01/templates/menu.html
<div class="static-menu">
    {% for item in menu_list %}
        <a href="{{ item.url }}">
            <span class="icon-wrap"><i class="{{ item.icon }}"></i></span> {{ item.title }} </a>
    {% endfor %}
</div>

luffy_rbac/app01/templates/payment_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

luffy_rbac/app01/templates/payment_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

luffy_rbac/app01/templates/payment_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="luffy-container">
        <div style="margin: 5px 0;">
            <a class="btn btn-success" href="/payment/add/">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加缴费记录
            </a>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>客户姓名</th>
                <th>金额</th>
                <th>付费时间</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.customer.name }}</td>
                    <td>{{ row.money }}</td>
                    <td>{{ row.create_time|date:"Y-m-d H:i:s" }}</td>
                    <td>
                        <a style="color: #333333;" href="/payment/edit/{{ row.id }}/">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="/payment/del/{{ row.id }}/"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

luffy_rbac/rbac/templates/rbac/menu.html
{#<div class="static-menu">#}
{#    {% for item in menu_list %}#}
{#        <a href="{{ item.url }}" class="{{ item.active }}">#}
{#            <span class="icon-wrap"><i class="{{ item.icon }}"></i></span> {{ item.title }} </a>#}
{#    {% endfor %}#}
{#</div>#}

{#    """#}
{#        {2: {'title': '用户管理', 'icon': 'fa fa-bathtub', 'children': [{'title': '客户列表', 'url': '/customer/list/'}]}, 1: {'title': '信息管理', 'icon': 'fa fa-bathtub', 'children': [{'title': '订单列表', 'url': '/payment/list/'}]}} #}
{#    """#}

<div class="static-menu">
    {% for item in menu_dict.values %}
        <div class="item">
            <div class="header">{{ item.title }}</div>
            <div class="body">
                {% for node in item.children %}
                    <a href="{{ node.url }}">{{ node.title }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

{#<div class="static-menu">#}
{#    <div class="item">#}
{#        <div class="header">一级菜单</div>#}
{#        <div class="body">#}
{#            <a>二级菜单</a>#}
{#        </div>#}
{#    </div>#}
{#</div>#}